// <auto-generated />
using System;
using HRDCD.Delivery.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRDCD.Delivery.Database.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRDCD.Delivery.DataModel.Entity.DeliveryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("del_date");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_status");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ins_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_del");

                    b.Property<long>("OrderEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_entity_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("Id");

                    b.HasIndex("OrderEntityId")
                        .IsUnique();

                    b.ToTable("delivery", (string)null);
                });

            modelBuilder.Entity("HRDCD.Delivery.DataModel.Entity.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("del_date");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ins_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_del");

                    b.Property<string>("OrderDescription")
                        .HasColumnType("text")
                        .HasColumnName("order_desc");

                    b.Property<string>("OrderName")
                        .HasColumnType("text")
                        .HasColumnName("order_name");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_num");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("HRDCD.Delivery.DataModel.Entity.DeliveryEntity", b =>
                {
                    b.HasOne("HRDCD.Delivery.DataModel.Entity.OrderEntity", "OrderEntity")
                        .WithMany("DeliveryEntities")
                        .HasForeignKey("OrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderEntity");
                });

            modelBuilder.Entity("HRDCD.Delivery.DataModel.Entity.OrderEntity", b =>
                {
                    b.Navigation("DeliveryEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
